#!/usr/bin/env node

/**
 * Generate Asset Mapping Script
 * 
 * This script automatically generates the asset mapping for the image URL transformer
 * by scanning the assets directory and creating the necessary imports and mappings.
 * 
 * Usage: node scripts/generateAssetMapping.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const ASSETS_DIR = path.join(__dirname, '../src/assets');
const OUTPUT_FILE = path.join(__dirname, '../src/utils/imageUrlTransformer.ts');

// Asset directories to scan
const ASSET_DIRS = [
  { dir: '16', ext: 'svg', prefix: 'Icons16' },
  { dir: '24', ext: 'svg', prefix: 'Icons24' },
  { dir: '32', ext: 'svg', prefix: 'Icons32' },
  { dir: 'navigation', ext: 'svg', prefix: 'NavigationIcons' },
  { dir: 'avatars', ext: ['jpg', 'jpeg', 'png'], prefix: 'AvatarImages' },
  { dir: 'promo-images', ext: ['jpg', 'jpeg', 'png'], prefix: 'PromoImages' },
];

/**
 * Get all files in a directory recursively
 */
function getAllFiles(dirPath, arrayOfFiles = []) {
  const files = fs.readdirSync(dirPath);

  files.forEach(file => {
    const fullPath = path.join(dirPath, file);
    if (fs.statSync(fullPath).isDirectory()) {
      arrayOfFiles = getAllFiles(fullPath, arrayOfFiles);
    } else {
      arrayOfFiles.push(fullPath);
    }
  });

  return arrayOfFiles;
}

/**
 * Generate import statements for assets
 */
function generateImports() {
  let imports = [];
  let assetMapEntries = [];

  ASSET_DIRS.forEach(({ dir, ext, prefix }) => {
    const assetDir = path.join(ASSETS_DIR, dir);
    if (!fs.existsSync(assetDir)) return;

    const files = getAllFiles(assetDir);
    const extensions = Array.isArray(ext) ? ext : [ext];

    files.forEach(file => {
      const relativePath = path.relative(ASSETS_DIR, file);
      const fileExt = path.extname(file).substring(1);
      
      if (extensions.includes(fileExt)) {
        const importName = `${prefix}_${path.basename(file, path.extname(file))}`.replace(/[^a-zA-Z0-9_]/g, '_');
        const importPath = `src/assets/${relativePath}`;
        
        imports.push(`import ${importName} from '${importPath}';`);
        
        // Create the expected path pattern
        const expectedPath = `/sites/interventions-hub/src/assets/${relativePath}`;
        assetMapEntries.push(`  ['${expectedPath}', ${importName}]`);
      }
    });
  });

  return { imports, assetMapEntries };
}

/**
 * Generate the complete transformer file
 */
function generateTransformerFile() {
  const { imports, assetMapEntries } = generateImports();

  const fileContent = `/**
 * Image URL Transformer
 * 
 * This utility handles transforming image URLs from layout JSON files
 * to work in both development and production environments.
 * 
 * In development: URLs like "/sites/interventions-hub/src/assets/24/device-mobile.svg" work
 * In production: Assets are bundled and need to be referenced differently
 * 
 * This file is auto-generated by scripts/generateAssetMapping.js
 * Run "node scripts/generateAssetMapping.js" to update the asset mappings
 */

// Import commonly used assets that are referenced in layouts
// This ensures they're included in the bundle and we can get their URLs
${imports.join('\n')}

// Create a mapping of path patterns to actual imported assets
const assetMap = new Map<string, string>([
${assetMapEntries.join(',\n')}
]);

/**
 * Transform an image URL to work in the current environment
 * 
 * @param url - The image URL from the layout JSON
 * @returns The transformed URL that will work in both dev and production
 */
export const transformImageUrl = (url: string): string => {
  if (!url) return '';
  
  // If it's already a full URL or data URL, return as is
  if (url.startsWith('http') || url.startsWith('data:')) {
    return url;
  }
  
  // If it's a relative path that starts with /, try to transform it
  if (url.startsWith('/')) {
    // Check if we have a mapping for this path
    const transformedUrl = assetMap.get(url);
    if (transformedUrl) {
      return transformedUrl;
    }
    
    // If no mapping found, return the original URL (might work in development)
    // In production, this will likely fail, but we can't map everything
    console.warn(\`No asset mapping found for URL: \${url}\`);
    return url;
  }
  
  // If it's a Vite-processed URL (already transformed), return as is
  return url;
};

/**
 * Transform all image URLs in a layout object
 * 
 * @param layout - The layout object containing image URLs
 * @returns The layout object with transformed image URLs
 */
export const transformLayoutImageUrls = (layout: any): any => {
  if (!layout) return layout;
  
  // Deep clone the layout to avoid mutating the original
  const transformed = JSON.parse(JSON.stringify(layout));
  
  // Recursively transform image URLs in the layout
  const transformObject = (obj: any): any => {
    if (Array.isArray(obj)) {
      return obj.map(transformObject);
    }
    
    if (obj && typeof obj === 'object') {
      const result: any = {};
      for (const [key, value] of Object.entries(obj)) {
        if (key === 'image' || key === 'icon') {
          // Transform image/icon URLs
          result[key] = transformImageUrl(value as string);
        } else if (key === 'image1' || key === 'image2') {
          // Transform stacked avatar images
          result[key] = transformImageUrl(value as string);
        } else {
          // Recursively transform nested objects
          result[key] = transformObject(value);
        }
      }
      return result;
    }
    
    return obj;
  };
  
  return transformObject(transformed);
};

/**
 * Transform image URLs in multiple layouts
 * 
 * @param layouts - Array of layout objects
 * @returns Array of layout objects with transformed image URLs
 */
export const transformLayoutsImageUrls = (layouts: any[]): any[] => {
  return layouts.map(transformLayoutImageUrls);
};
`;

  return fileContent;
}

/**
 * Main function
 */
function main() {
  try {
    console.log('Generating asset mapping...');
    
    const fileContent = generateTransformerFile();
    
    // Write the file
    fs.writeFileSync(OUTPUT_FILE, fileContent);
    
    console.log(`✅ Asset mapping generated successfully at ${OUTPUT_FILE}`);
    console.log('💡 Run this script whenever you add new assets to update the mappings');
    
  } catch (error) {
    console.error('❌ Error generating asset mapping:', error);
    process.exit(1);
  }
}

// Run the script
main();
